[project]
name = "refet"
version = "0.5.0"
authors = [
    { name="Charles Morton", email="charles.morton@dri.edu" },
]
description = "ASCE Standardized Reference Evapotranspiration Functions"
readme = "README.rst"
requires-python = ">=3.11"
license = "Apache-2.0"
license-files = ["LICENSE.txt"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.0.0",
]

[project.urls]
"Homepage" = "https://github.com/WSWUP/RefET"
"Bug Tracker" = "https://github.com/WSWUP/RefET/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = [
    "pandas",
    "pytz",
    "pytest",
]
